#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Monolito4amDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_fotos_productos(tbl_fotos_productos instance);
    partial void Updatetbl_fotos_productos(tbl_fotos_productos instance);
    partial void Deletetbl_fotos_productos(tbl_fotos_productos instance);
    partial void Inserttbl_productos(tbl_productos instance);
    partial void Updatetbl_productos(tbl_productos instance);
    partial void Deletetbl_productos(tbl_productos instance);
    partial void Inserttbl_productos_eliminado(tbl_productos_eliminado instance);
    partial void Updatetbl_productos_eliminado(tbl_productos_eliminado instance);
    partial void Deletetbl_productos_eliminado(tbl_productos_eliminado instance);
    partial void Inserttbl_proveedor(tbl_proveedor instance);
    partial void Updatetbl_proveedor(tbl_proveedor instance);
    partial void Deletetbl_proveedor(tbl_proveedor instance);
    partial void Inserttbl_proveedor_eliminado(tbl_proveedor_eliminado instance);
    partial void Updatetbl_proveedor_eliminado(tbl_proveedor_eliminado instance);
    partial void Deletetbl_proveedor_eliminado(tbl_proveedor_eliminado instance);
    partial void Inserttbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Updatetbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Deletetbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Inserttbl_usario(tbl_usario instance);
    partial void Updatetbl_usario(tbl_usario instance);
    partial void Deletetbl_usario(tbl_usario instance);
    partial void Inserttbl_usuario_foto(tbl_usuario_foto instance);
    partial void Updatetbl_usuario_foto(tbl_usuario_foto instance);
    partial void Deletetbl_usuario_foto(tbl_usuario_foto instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.Monolito4amDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_fotos_productos> tbl_fotos_productos
		{
			get
			{
				return this.GetTable<tbl_fotos_productos>();
			}
		}
		
		public System.Data.Linq.Table<tbl_productos> tbl_productos
		{
			get
			{
				return this.GetTable<tbl_productos>();
			}
		}
		
		public System.Data.Linq.Table<tbl_productos_eliminado> tbl_productos_eliminado
		{
			get
			{
				return this.GetTable<tbl_productos_eliminado>();
			}
		}
		
		public System.Data.Linq.Table<tbl_proveedor> tbl_proveedor
		{
			get
			{
				return this.GetTable<tbl_proveedor>();
			}
		}
		
		public System.Data.Linq.Table<tbl_proveedor_eliminado> tbl_proveedor_eliminado
		{
			get
			{
				return this.GetTable<tbl_proveedor_eliminado>();
			}
		}
		
		public System.Data.Linq.Table<tbl_tipo_usuario> tbl_tipo_usuario
		{
			get
			{
				return this.GetTable<tbl_tipo_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usario> tbl_usario
		{
			get
			{
				return this.GetTable<tbl_usario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario_foto> tbl_usuario_foto
		{
			get
			{
				return this.GetTable<tbl_usuario_foto>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ReiniciarIdentityProveedor")]
		public int sp_ReiniciarIdentityProveedor()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ReiniciarIntentosDiarios")]
		public int sp_ReiniciarIntentosDiarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.desencriptacon", IsComposable=true)]
		public string desencriptacon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary clave)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clave).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.encriptacon", IsComposable=true)]
		public System.Data.Linq.Binary encriptacon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string clave)
		{
			return ((System.Data.Linq.Binary)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clave).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_fotos_productos")]
	public partial class tbl_fotos_productos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fpro_id;
		
		private int _pro_id;
		
		private string _fpro_ruta_imagen;
		
		private string _fpro_nombre_archivo;
		
		private System.Nullable<System.DateTime> _fpro_fecha_subida;
		
		private System.Nullable<bool> _fpro_es_principal;
		
		private EntityRef<tbl_productos> _tbl_productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfpro_idChanging(int value);
    partial void Onfpro_idChanged();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onfpro_ruta_imagenChanging(string value);
    partial void Onfpro_ruta_imagenChanged();
    partial void Onfpro_nombre_archivoChanging(string value);
    partial void Onfpro_nombre_archivoChanged();
    partial void Onfpro_fecha_subidaChanging(System.Nullable<System.DateTime> value);
    partial void Onfpro_fecha_subidaChanged();
    partial void Onfpro_es_principalChanging(System.Nullable<bool> value);
    partial void Onfpro_es_principalChanged();
    #endregion
		
		public tbl_fotos_productos()
		{
			this._tbl_productos = default(EntityRef<tbl_productos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fpro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fpro_id
		{
			get
			{
				return this._fpro_id;
			}
			set
			{
				if ((this._fpro_id != value))
				{
					this.Onfpro_idChanging(value);
					this.SendPropertyChanging();
					this._fpro_id = value;
					this.SendPropertyChanged("fpro_id");
					this.Onfpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL")]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					if (this._tbl_productos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fpro_ruta_imagen", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string fpro_ruta_imagen
		{
			get
			{
				return this._fpro_ruta_imagen;
			}
			set
			{
				if ((this._fpro_ruta_imagen != value))
				{
					this.Onfpro_ruta_imagenChanging(value);
					this.SendPropertyChanging();
					this._fpro_ruta_imagen = value;
					this.SendPropertyChanged("fpro_ruta_imagen");
					this.Onfpro_ruta_imagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fpro_nombre_archivo", DbType="VarChar(150)")]
		public string fpro_nombre_archivo
		{
			get
			{
				return this._fpro_nombre_archivo;
			}
			set
			{
				if ((this._fpro_nombre_archivo != value))
				{
					this.Onfpro_nombre_archivoChanging(value);
					this.SendPropertyChanging();
					this._fpro_nombre_archivo = value;
					this.SendPropertyChanged("fpro_nombre_archivo");
					this.Onfpro_nombre_archivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fpro_fecha_subida", DbType="DateTime")]
		public System.Nullable<System.DateTime> fpro_fecha_subida
		{
			get
			{
				return this._fpro_fecha_subida;
			}
			set
			{
				if ((this._fpro_fecha_subida != value))
				{
					this.Onfpro_fecha_subidaChanging(value);
					this.SendPropertyChanging();
					this._fpro_fecha_subida = value;
					this.SendPropertyChanged("fpro_fecha_subida");
					this.Onfpro_fecha_subidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fpro_es_principal", DbType="Bit")]
		public System.Nullable<bool> fpro_es_principal
		{
			get
			{
				return this._fpro_es_principal;
			}
			set
			{
				if ((this._fpro_es_principal != value))
				{
					this.Onfpro_es_principalChanging(value);
					this.SendPropertyChanging();
					this._fpro_es_principal = value;
					this.SendPropertyChanged("fpro_es_principal");
					this.Onfpro_es_principalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_productos_tbl_fotos_productos", Storage="_tbl_productos", ThisKey="pro_id", OtherKey="pro_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_productos tbl_productos
		{
			get
			{
				return this._tbl_productos.Entity;
			}
			set
			{
				tbl_productos previousValue = this._tbl_productos.Entity;
				if (((previousValue != value) 
							|| (this._tbl_productos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_productos.Entity = null;
						previousValue.tbl_fotos_productos.Remove(this);
					}
					this._tbl_productos.Entity = value;
					if ((value != null))
					{
						value.tbl_fotos_productos.Add(this);
						this._pro_id = value.pro_id;
					}
					else
					{
						this._pro_id = default(int);
					}
					this.SendPropertyChanged("tbl_productos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_productos")]
	public partial class tbl_productos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_nombre;
		
		private System.Nullable<int> _pro_cantidad;
		
		private System.Nullable<decimal> _pro_precio;
		
		private System.Nullable<char> _pro_estado;
		
		private System.Nullable<int> _prov_id;
		
		private string _pro_codigo;
		
		private string _pro_descripcion;
		
		private EntitySet<tbl_fotos_productos> _tbl_fotos_productos;
		
		private EntityRef<tbl_proveedor> _tbl_proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_cantidadChanging(System.Nullable<int> value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_precioChanging(System.Nullable<decimal> value);
    partial void Onpro_precioChanged();
    partial void Onpro_estadoChanging(System.Nullable<char> value);
    partial void Onpro_estadoChanged();
    partial void Onprov_idChanging(System.Nullable<int> value);
    partial void Onprov_idChanged();
    partial void Onpro_codigoChanging(string value);
    partial void Onpro_codigoChanged();
    partial void Onpro_descripcionChanging(string value);
    partial void Onpro_descripcionChanged();
    #endregion
		
		public tbl_productos()
		{
			this._tbl_fotos_productos = new EntitySet<tbl_fotos_productos>(new Action<tbl_fotos_productos>(this.attach_tbl_fotos_productos), new Action<tbl_fotos_productos>(this.detach_tbl_fotos_productos));
			this._tbl_proveedor = default(EntityRef<tbl_proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="VarChar(50)")]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int")]
		public System.Nullable<int> pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> pro_precio
		{
			get
			{
				return this._pro_precio;
			}
			set
			{
				if ((this._pro_precio != value))
				{
					this.Onpro_precioChanging(value);
					this.SendPropertyChanging();
					this._pro_precio = value;
					this.SendPropertyChanged("pro_precio");
					this.Onpro_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Char(1)")]
		public System.Nullable<char> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", DbType="Int")]
		public System.Nullable<int> prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					if (this._tbl_proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_codigo", DbType="VarChar(50)")]
		public string pro_codigo
		{
			get
			{
				return this._pro_codigo;
			}
			set
			{
				if ((this._pro_codigo != value))
				{
					this.Onpro_codigoChanging(value);
					this.SendPropertyChanging();
					this._pro_codigo = value;
					this.SendPropertyChanged("pro_codigo");
					this.Onpro_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_descripcion", DbType="VarChar(250)")]
		public string pro_descripcion
		{
			get
			{
				return this._pro_descripcion;
			}
			set
			{
				if ((this._pro_descripcion != value))
				{
					this.Onpro_descripcionChanging(value);
					this.SendPropertyChanging();
					this._pro_descripcion = value;
					this.SendPropertyChanged("pro_descripcion");
					this.Onpro_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_productos_tbl_fotos_productos", Storage="_tbl_fotos_productos", ThisKey="pro_id", OtherKey="pro_id")]
		public EntitySet<tbl_fotos_productos> tbl_fotos_productos
		{
			get
			{
				return this._tbl_fotos_productos;
			}
			set
			{
				this._tbl_fotos_productos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_productos", Storage="_tbl_proveedor", ThisKey="prov_id", OtherKey="prov_id", IsForeignKey=true)]
		public tbl_proveedor tbl_proveedor
		{
			get
			{
				return this._tbl_proveedor.Entity;
			}
			set
			{
				tbl_proveedor previousValue = this._tbl_proveedor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_proveedor.Entity = null;
						previousValue.tbl_productos.Remove(this);
					}
					this._tbl_proveedor.Entity = value;
					if ((value != null))
					{
						value.tbl_productos.Add(this);
						this._prov_id = value.prov_id;
					}
					else
					{
						this._prov_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_fotos_productos(tbl_fotos_productos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_productos = this;
		}
		
		private void detach_tbl_fotos_productos(tbl_fotos_productos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_productos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_productos_eliminado")]
	public partial class tbl_productos_eliminado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_nombre;
		
		private string _pro_codigo;
		
		private string _pro_descripcion;
		
		private System.Nullable<int> _pro_cantidad;
		
		private System.Nullable<decimal> _pro_precio;
		
		private System.Nullable<int> _prov_id;
		
		private System.Nullable<char> _pro_estado;
		
		private System.Nullable<System.DateTime> _fecha_eliminacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_codigoChanging(string value);
    partial void Onpro_codigoChanged();
    partial void Onpro_descripcionChanging(string value);
    partial void Onpro_descripcionChanged();
    partial void Onpro_cantidadChanging(System.Nullable<int> value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_precioChanging(System.Nullable<decimal> value);
    partial void Onpro_precioChanged();
    partial void Onprov_idChanging(System.Nullable<int> value);
    partial void Onprov_idChanged();
    partial void Onpro_estadoChanging(System.Nullable<char> value);
    partial void Onpro_estadoChanged();
    partial void Onfecha_eliminacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_eliminacionChanged();
    #endregion
		
		public tbl_productos_eliminado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="VarChar(50)")]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_codigo", DbType="VarChar(50)")]
		public string pro_codigo
		{
			get
			{
				return this._pro_codigo;
			}
			set
			{
				if ((this._pro_codigo != value))
				{
					this.Onpro_codigoChanging(value);
					this.SendPropertyChanging();
					this._pro_codigo = value;
					this.SendPropertyChanged("pro_codigo");
					this.Onpro_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_descripcion", DbType="VarChar(250)")]
		public string pro_descripcion
		{
			get
			{
				return this._pro_descripcion;
			}
			set
			{
				if ((this._pro_descripcion != value))
				{
					this.Onpro_descripcionChanging(value);
					this.SendPropertyChanging();
					this._pro_descripcion = value;
					this.SendPropertyChanged("pro_descripcion");
					this.Onpro_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int")]
		public System.Nullable<int> pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> pro_precio
		{
			get
			{
				return this._pro_precio;
			}
			set
			{
				if ((this._pro_precio != value))
				{
					this.Onpro_precioChanging(value);
					this.SendPropertyChanging();
					this._pro_precio = value;
					this.SendPropertyChanged("pro_precio");
					this.Onpro_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", DbType="Int")]
		public System.Nullable<int> prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Char(1)")]
		public System.Nullable<char> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_eliminacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_eliminacion
		{
			get
			{
				return this._fecha_eliminacion;
			}
			set
			{
				if ((this._fecha_eliminacion != value))
				{
					this.Onfecha_eliminacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_eliminacion = value;
					this.SendPropertyChanged("fecha_eliminacion");
					this.Onfecha_eliminacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_proveedor")]
	public partial class tbl_proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prov_id;
		
		private string _prov_nombre;
		
		private System.Nullable<char> _prov_estado;
		
		private string _prov_ruc;
		
		private string _prov_telefono;
		
		private string _prov_correo;
		
		private EntitySet<tbl_productos> _tbl_productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    partial void Onprov_nombreChanging(string value);
    partial void Onprov_nombreChanged();
    partial void Onprov_estadoChanging(System.Nullable<char> value);
    partial void Onprov_estadoChanged();
    partial void Onprov_rucChanging(string value);
    partial void Onprov_rucChanged();
    partial void Onprov_telefonoChanging(string value);
    partial void Onprov_telefonoChanged();
    partial void Onprov_correoChanging(string value);
    partial void Onprov_correoChanged();
    #endregion
		
		public tbl_proveedor()
		{
			this._tbl_productos = new EntitySet<tbl_productos>(new Action<tbl_productos>(this.attach_tbl_productos), new Action<tbl_productos>(this.detach_tbl_productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_nombre", DbType="VarChar(50)")]
		public string prov_nombre
		{
			get
			{
				return this._prov_nombre;
			}
			set
			{
				if ((this._prov_nombre != value))
				{
					this.Onprov_nombreChanging(value);
					this.SendPropertyChanging();
					this._prov_nombre = value;
					this.SendPropertyChanged("prov_nombre");
					this.Onprov_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_estado", DbType="Char(1)")]
		public System.Nullable<char> prov_estado
		{
			get
			{
				return this._prov_estado;
			}
			set
			{
				if ((this._prov_estado != value))
				{
					this.Onprov_estadoChanging(value);
					this.SendPropertyChanging();
					this._prov_estado = value;
					this.SendPropertyChanged("prov_estado");
					this.Onprov_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_ruc", DbType="VarChar(13)")]
		public string prov_ruc
		{
			get
			{
				return this._prov_ruc;
			}
			set
			{
				if ((this._prov_ruc != value))
				{
					this.Onprov_rucChanging(value);
					this.SendPropertyChanging();
					this._prov_ruc = value;
					this.SendPropertyChanged("prov_ruc");
					this.Onprov_rucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_telefono", DbType="VarChar(15)")]
		public string prov_telefono
		{
			get
			{
				return this._prov_telefono;
			}
			set
			{
				if ((this._prov_telefono != value))
				{
					this.Onprov_telefonoChanging(value);
					this.SendPropertyChanging();
					this._prov_telefono = value;
					this.SendPropertyChanged("prov_telefono");
					this.Onprov_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_correo", DbType="VarChar(100)")]
		public string prov_correo
		{
			get
			{
				return this._prov_correo;
			}
			set
			{
				if ((this._prov_correo != value))
				{
					this.Onprov_correoChanging(value);
					this.SendPropertyChanging();
					this._prov_correo = value;
					this.SendPropertyChanged("prov_correo");
					this.Onprov_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_productos", Storage="_tbl_productos", ThisKey="prov_id", OtherKey="prov_id")]
		public EntitySet<tbl_productos> tbl_productos
		{
			get
			{
				return this._tbl_productos;
			}
			set
			{
				this._tbl_productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_productos(tbl_productos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = this;
		}
		
		private void detach_tbl_productos(tbl_productos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_proveedor_eliminado")]
	public partial class tbl_proveedor_eliminado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prov_id;
		
		private string _prov_nombre;
		
		private System.Nullable<char> _prov_estado;
		
		private string _prov_ruc;
		
		private string _prov_telefono;
		
		private string _prov_correo;
		
		private System.Nullable<System.DateTime> _fecha_eliminacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    partial void Onprov_nombreChanging(string value);
    partial void Onprov_nombreChanged();
    partial void Onprov_estadoChanging(System.Nullable<char> value);
    partial void Onprov_estadoChanged();
    partial void Onprov_rucChanging(string value);
    partial void Onprov_rucChanged();
    partial void Onprov_telefonoChanging(string value);
    partial void Onprov_telefonoChanged();
    partial void Onprov_correoChanging(string value);
    partial void Onprov_correoChanged();
    partial void Onfecha_eliminacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_eliminacionChanged();
    #endregion
		
		public tbl_proveedor_eliminado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_nombre", DbType="VarChar(50)")]
		public string prov_nombre
		{
			get
			{
				return this._prov_nombre;
			}
			set
			{
				if ((this._prov_nombre != value))
				{
					this.Onprov_nombreChanging(value);
					this.SendPropertyChanging();
					this._prov_nombre = value;
					this.SendPropertyChanged("prov_nombre");
					this.Onprov_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_estado", DbType="Char(1)")]
		public System.Nullable<char> prov_estado
		{
			get
			{
				return this._prov_estado;
			}
			set
			{
				if ((this._prov_estado != value))
				{
					this.Onprov_estadoChanging(value);
					this.SendPropertyChanging();
					this._prov_estado = value;
					this.SendPropertyChanged("prov_estado");
					this.Onprov_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_ruc", DbType="VarChar(13)")]
		public string prov_ruc
		{
			get
			{
				return this._prov_ruc;
			}
			set
			{
				if ((this._prov_ruc != value))
				{
					this.Onprov_rucChanging(value);
					this.SendPropertyChanging();
					this._prov_ruc = value;
					this.SendPropertyChanged("prov_ruc");
					this.Onprov_rucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_telefono", DbType="VarChar(15)")]
		public string prov_telefono
		{
			get
			{
				return this._prov_telefono;
			}
			set
			{
				if ((this._prov_telefono != value))
				{
					this.Onprov_telefonoChanging(value);
					this.SendPropertyChanging();
					this._prov_telefono = value;
					this.SendPropertyChanged("prov_telefono");
					this.Onprov_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_correo", DbType="VarChar(100)")]
		public string prov_correo
		{
			get
			{
				return this._prov_correo;
			}
			set
			{
				if ((this._prov_correo != value))
				{
					this.Onprov_correoChanging(value);
					this.SendPropertyChanging();
					this._prov_correo = value;
					this.SendPropertyChanged("prov_correo");
					this.Onprov_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_eliminacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_eliminacion
		{
			get
			{
				return this._fecha_eliminacion;
			}
			set
			{
				if ((this._fecha_eliminacion != value))
				{
					this.Onfecha_eliminacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_eliminacion = value;
					this.SendPropertyChanged("fecha_eliminacion");
					this.Onfecha_eliminacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tipo_usuario")]
	public partial class tbl_tipo_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tusu_id;
		
		private string _tusu_nombre;
		
		private System.Nullable<char> _tusu_estado;
		
		private EntitySet<tbl_usario> _tbl_usario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontusu_idChanging(int value);
    partial void Ontusu_idChanged();
    partial void Ontusu_nombreChanging(string value);
    partial void Ontusu_nombreChanged();
    partial void Ontusu_estadoChanging(System.Nullable<char> value);
    partial void Ontusu_estadoChanged();
    #endregion
		
		public tbl_tipo_usuario()
		{
			this._tbl_usario = new EntitySet<tbl_usario>(new Action<tbl_usario>(this.attach_tbl_usario), new Action<tbl_usario>(this.detach_tbl_usario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_nombre", DbType="VarChar(50)")]
		public string tusu_nombre
		{
			get
			{
				return this._tusu_nombre;
			}
			set
			{
				if ((this._tusu_nombre != value))
				{
					this.Ontusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._tusu_nombre = value;
					this.SendPropertyChanged("tusu_nombre");
					this.Ontusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_estado", DbType="Char(1)")]
		public System.Nullable<char> tusu_estado
		{
			get
			{
				return this._tusu_estado;
			}
			set
			{
				if ((this._tusu_estado != value))
				{
					this.Ontusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._tusu_estado = value;
					this.SendPropertyChanged("tusu_estado");
					this.Ontusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_usuario_tbl_usario", Storage="_tbl_usario", ThisKey="tusu_id", OtherKey="tusu_id")]
		public EntitySet<tbl_usario> tbl_usario
		{
			get
			{
				return this._tbl_usario;
			}
			set
			{
				this._tbl_usario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usario(tbl_usario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_usuario = this;
		}
		
		private void detach_tbl_usario(tbl_usario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usario")]
	public partial class tbl_usario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_cedula;
		
		private string _usu_nombres;
		
		private string _usu_apellidos;
		
		private string _usu_direccion;
		
		private string _usu_celular;
		
		private string _usu_correo;
		
		private System.Nullable<System.DateTime> _usu_fecha_creacion;
		
		private System.Nullable<System.DateTime> _usu_fecha_cumple;
		
		private string _usu_nick;
		
		private System.Data.Linq.Binary _usu_contraseña;
		
		private System.Nullable<int> _usu_intentos;
		
		private System.Nullable<char> _usu_estado;
		
		private System.Nullable<int> _tusu_id;
		
		private System.Nullable<System.DateTime> _usu_fecha_ultimo_intento;
		
		private System.Data.Linq.Binary _usu_codigo_OTP;
		
		private bool _usu_bloqueado;
		
		private System.Nullable<int> _usu_record;
		
		private EntitySet<tbl_usuario_foto> _tbl_usuario_foto;
		
		private EntityRef<tbl_tipo_usuario> _tbl_tipo_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_cedulaChanging(string value);
    partial void Onusu_cedulaChanged();
    partial void Onusu_nombresChanging(string value);
    partial void Onusu_nombresChanged();
    partial void Onusu_apellidosChanging(string value);
    partial void Onusu_apellidosChanged();
    partial void Onusu_direccionChanging(string value);
    partial void Onusu_direccionChanged();
    partial void Onusu_celularChanging(string value);
    partial void Onusu_celularChanged();
    partial void Onusu_correoChanging(string value);
    partial void Onusu_correoChanged();
    partial void Onusu_fecha_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_creacionChanged();
    partial void Onusu_fecha_cumpleChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_cumpleChanged();
    partial void Onusu_nickChanging(string value);
    partial void Onusu_nickChanged();
    partial void Onusu_contraseñaChanging(System.Data.Linq.Binary value);
    partial void Onusu_contraseñaChanged();
    partial void Onusu_intentosChanging(System.Nullable<int> value);
    partial void Onusu_intentosChanged();
    partial void Onusu_estadoChanging(System.Nullable<char> value);
    partial void Onusu_estadoChanged();
    partial void Ontusu_idChanging(System.Nullable<int> value);
    partial void Ontusu_idChanged();
    partial void Onusu_fecha_ultimo_intentoChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_ultimo_intentoChanged();
    partial void Onusu_codigo_OTPChanging(System.Data.Linq.Binary value);
    partial void Onusu_codigo_OTPChanged();
    partial void Onusu_bloqueadoChanging(bool value);
    partial void Onusu_bloqueadoChanged();
    partial void Onusu_recordChanging(System.Nullable<int> value);
    partial void Onusu_recordChanged();
    #endregion
		
		public tbl_usario()
		{
			this._tbl_usuario_foto = new EntitySet<tbl_usuario_foto>(new Action<tbl_usuario_foto>(this.attach_tbl_usuario_foto), new Action<tbl_usuario_foto>(this.detach_tbl_usuario_foto));
			this._tbl_tipo_usuario = default(EntityRef<tbl_tipo_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_cedula", DbType="VarChar(10)")]
		public string usu_cedula
		{
			get
			{
				return this._usu_cedula;
			}
			set
			{
				if ((this._usu_cedula != value))
				{
					this.Onusu_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usu_cedula = value;
					this.SendPropertyChanged("usu_cedula");
					this.Onusu_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombres", DbType="VarChar(50)")]
		public string usu_nombres
		{
			get
			{
				return this._usu_nombres;
			}
			set
			{
				if ((this._usu_nombres != value))
				{
					this.Onusu_nombresChanging(value);
					this.SendPropertyChanging();
					this._usu_nombres = value;
					this.SendPropertyChanged("usu_nombres");
					this.Onusu_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_apellidos", DbType="VarChar(50)")]
		public string usu_apellidos
		{
			get
			{
				return this._usu_apellidos;
			}
			set
			{
				if ((this._usu_apellidos != value))
				{
					this.Onusu_apellidosChanging(value);
					this.SendPropertyChanging();
					this._usu_apellidos = value;
					this.SendPropertyChanged("usu_apellidos");
					this.Onusu_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_direccion", DbType="VarChar(50)")]
		public string usu_direccion
		{
			get
			{
				return this._usu_direccion;
			}
			set
			{
				if ((this._usu_direccion != value))
				{
					this.Onusu_direccionChanging(value);
					this.SendPropertyChanging();
					this._usu_direccion = value;
					this.SendPropertyChanged("usu_direccion");
					this.Onusu_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_celular", DbType="VarChar(10)")]
		public string usu_celular
		{
			get
			{
				return this._usu_celular;
			}
			set
			{
				if ((this._usu_celular != value))
				{
					this.Onusu_celularChanging(value);
					this.SendPropertyChanging();
					this._usu_celular = value;
					this.SendPropertyChanged("usu_celular");
					this.Onusu_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_correo", DbType="VarChar(150)")]
		public string usu_correo
		{
			get
			{
				return this._usu_correo;
			}
			set
			{
				if ((this._usu_correo != value))
				{
					this.Onusu_correoChanging(value);
					this.SendPropertyChanging();
					this._usu_correo = value;
					this.SendPropertyChanged("usu_correo");
					this.Onusu_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> usu_fecha_creacion
		{
			get
			{
				return this._usu_fecha_creacion;
			}
			set
			{
				if ((this._usu_fecha_creacion != value))
				{
					this.Onusu_fecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_creacion = value;
					this.SendPropertyChanged("usu_fecha_creacion");
					this.Onusu_fecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_cumple", DbType="Date")]
		public System.Nullable<System.DateTime> usu_fecha_cumple
		{
			get
			{
				return this._usu_fecha_cumple;
			}
			set
			{
				if ((this._usu_fecha_cumple != value))
				{
					this.Onusu_fecha_cumpleChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_cumple = value;
					this.SendPropertyChanged("usu_fecha_cumple");
					this.Onusu_fecha_cumpleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nick", DbType="VarChar(50)")]
		public string usu_nick
		{
			get
			{
				return this._usu_nick;
			}
			set
			{
				if ((this._usu_nick != value))
				{
					this.Onusu_nickChanging(value);
					this.SendPropertyChanging();
					this._usu_nick = value;
					this.SendPropertyChanged("usu_nick");
					this.Onusu_nickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_contraseña", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary usu_contraseña
		{
			get
			{
				return this._usu_contraseña;
			}
			set
			{
				if ((this._usu_contraseña != value))
				{
					this.Onusu_contraseñaChanging(value);
					this.SendPropertyChanging();
					this._usu_contraseña = value;
					this.SendPropertyChanged("usu_contraseña");
					this.Onusu_contraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_intentos", DbType="Int")]
		public System.Nullable<int> usu_intentos
		{
			get
			{
				return this._usu_intentos;
			}
			set
			{
				if ((this._usu_intentos != value))
				{
					this.Onusu_intentosChanging(value);
					this.SendPropertyChanging();
					this._usu_intentos = value;
					this.SendPropertyChanged("usu_intentos");
					this.Onusu_intentosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_estado", DbType="Char(1)")]
		public System.Nullable<char> usu_estado
		{
			get
			{
				return this._usu_estado;
			}
			set
			{
				if ((this._usu_estado != value))
				{
					this.Onusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._usu_estado = value;
					this.SendPropertyChanged("usu_estado");
					this.Onusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", DbType="Int")]
		public System.Nullable<int> tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					if (this._tbl_tipo_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_ultimo_intento", DbType="DateTime")]
		public System.Nullable<System.DateTime> usu_fecha_ultimo_intento
		{
			get
			{
				return this._usu_fecha_ultimo_intento;
			}
			set
			{
				if ((this._usu_fecha_ultimo_intento != value))
				{
					this.Onusu_fecha_ultimo_intentoChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_ultimo_intento = value;
					this.SendPropertyChanged("usu_fecha_ultimo_intento");
					this.Onusu_fecha_ultimo_intentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_codigo_OTP", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary usu_codigo_OTP
		{
			get
			{
				return this._usu_codigo_OTP;
			}
			set
			{
				if ((this._usu_codigo_OTP != value))
				{
					this.Onusu_codigo_OTPChanging(value);
					this.SendPropertyChanging();
					this._usu_codigo_OTP = value;
					this.SendPropertyChanged("usu_codigo_OTP");
					this.Onusu_codigo_OTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_bloqueado", DbType="Bit NOT NULL")]
		public bool usu_bloqueado
		{
			get
			{
				return this._usu_bloqueado;
			}
			set
			{
				if ((this._usu_bloqueado != value))
				{
					this.Onusu_bloqueadoChanging(value);
					this.SendPropertyChanging();
					this._usu_bloqueado = value;
					this.SendPropertyChanged("usu_bloqueado");
					this.Onusu_bloqueadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_record", DbType="Int")]
		public System.Nullable<int> usu_record
		{
			get
			{
				return this._usu_record;
			}
			set
			{
				if ((this._usu_record != value))
				{
					this.Onusu_recordChanging(value);
					this.SendPropertyChanging();
					this._usu_record = value;
					this.SendPropertyChanged("usu_record");
					this.Onusu_recordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usario_tbl_usuario_foto", Storage="_tbl_usuario_foto", ThisKey="usu_id", OtherKey="usu_id")]
		public EntitySet<tbl_usuario_foto> tbl_usuario_foto
		{
			get
			{
				return this._tbl_usuario_foto;
			}
			set
			{
				this._tbl_usuario_foto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_usuario_tbl_usario", Storage="_tbl_tipo_usuario", ThisKey="tusu_id", OtherKey="tusu_id", IsForeignKey=true)]
		public tbl_tipo_usuario tbl_tipo_usuario
		{
			get
			{
				return this._tbl_tipo_usuario.Entity;
			}
			set
			{
				tbl_tipo_usuario previousValue = this._tbl_tipo_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_tipo_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_tipo_usuario.Entity = null;
						previousValue.tbl_usario.Remove(this);
					}
					this._tbl_tipo_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_usario.Add(this);
						this._tusu_id = value.tusu_id;
					}
					else
					{
						this._tusu_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_tipo_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usuario_foto(tbl_usuario_foto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usario = this;
		}
		
		private void detach_tbl_usuario_foto(tbl_usuario_foto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario_foto")]
	public partial class tbl_usuario_foto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _usu_id;
		
		private System.Data.Linq.Binary _foto;
		
		private string _nombre_archivo;
		
		private System.Nullable<System.DateTime> _fecha_subida;
		
		private System.Nullable<bool> _es_principal;
		
		private EntityRef<tbl_usario> _tbl_usario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void OnfotoChanging(System.Data.Linq.Binary value);
    partial void OnfotoChanged();
    partial void Onnombre_archivoChanging(string value);
    partial void Onnombre_archivoChanged();
    partial void Onfecha_subidaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_subidaChanged();
    partial void Ones_principalChanging(System.Nullable<bool> value);
    partial void Ones_principalChanged();
    #endregion
		
		public tbl_usuario_foto()
		{
			this._tbl_usario = default(EntityRef<tbl_usario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", DbType="Int NOT NULL")]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					if (this._tbl_usario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this.OnfotoChanging(value);
					this.SendPropertyChanging();
					this._foto = value;
					this.SendPropertyChanged("foto");
					this.OnfotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_archivo", DbType="VarChar(150)")]
		public string nombre_archivo
		{
			get
			{
				return this._nombre_archivo;
			}
			set
			{
				if ((this._nombre_archivo != value))
				{
					this.Onnombre_archivoChanging(value);
					this.SendPropertyChanging();
					this._nombre_archivo = value;
					this.SendPropertyChanged("nombre_archivo");
					this.Onnombre_archivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_subida", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_subida
		{
			get
			{
				return this._fecha_subida;
			}
			set
			{
				if ((this._fecha_subida != value))
				{
					this.Onfecha_subidaChanging(value);
					this.SendPropertyChanging();
					this._fecha_subida = value;
					this.SendPropertyChanged("fecha_subida");
					this.Onfecha_subidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_es_principal", DbType="Bit")]
		public System.Nullable<bool> es_principal
		{
			get
			{
				return this._es_principal;
			}
			set
			{
				if ((this._es_principal != value))
				{
					this.Ones_principalChanging(value);
					this.SendPropertyChanging();
					this._es_principal = value;
					this.SendPropertyChanged("es_principal");
					this.Ones_principalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usario_tbl_usuario_foto", Storage="_tbl_usario", ThisKey="usu_id", OtherKey="usu_id", IsForeignKey=true)]
		public tbl_usario tbl_usario
		{
			get
			{
				return this._tbl_usario.Entity;
			}
			set
			{
				tbl_usario previousValue = this._tbl_usario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_usario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_usario.Entity = null;
						previousValue.tbl_usuario_foto.Remove(this);
					}
					this._tbl_usario.Entity = value;
					if ((value != null))
					{
						value.tbl_usuario_foto.Add(this);
						this._usu_id = value.usu_id;
					}
					else
					{
						this._usu_id = default(int);
					}
					this.SendPropertyChanged("tbl_usario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
