//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.175,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString {
            get {
                return ((string)(this["Monolito4amConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.201,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString1 {
            get {
                return ((string)(this["Monolito4amConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.180,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString2 {
            get {
                return ((string)(this["Monolito4amConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.115,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString3 {
            get {
                return ((string)(this["Monolito4amConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.54,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString4 {
            get {
                return ((string)(this["Monolito4amConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.13.15,1433;Initial Catalog=Monolito4am;User ID=sa;Password=Jo" +
            "seabraham21;Encrypt=False")]
        public string Monolito4amConnectionString5 {
            get {
                return ((string)(this["Monolito4amConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.178,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString6 {
            get {
                return ((string)(this["Monolito4amConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.151,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString7 {
            get {
                return ((string)(this["Monolito4amConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.65,1433;Initial Catalog=Monolito4am;User ID=sa;Password=Jo" +
            "seabraham21;Encrypt=False")]
        public string Monolito4amConnectionString8 {
            get {
                return ((string)(this["Monolito4amConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.164,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString9 {
            get {
                return ((string)(this["Monolito4amConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.104,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString10 {
            get {
                return ((string)(this["Monolito4amConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.140,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString11 {
            get {
                return ((string)(this["Monolito4amConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.185,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString12 {
            get {
                return ((string)(this["Monolito4amConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.80,1433;Initial Catalog=Monolito4am;User ID=sa;Password=Jo" +
            "seabraham21;Encrypt=False")]
        public string Monolito4amConnectionString13 {
            get {
                return ((string)(this["Monolito4amConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.119,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString14 {
            get {
                return ((string)(this["Monolito4amConnectionString14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.131,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString15 {
            get {
                return ((string)(this["Monolito4amConnectionString15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.166,1433;Initial Catalog=Monolito4am;User ID=sa;Password=" +
            "Joseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString16 {
            get {
                return ((string)(this["Monolito4amConnectionString16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.12.110,1433;Initial Catalog=Monolito4am;User ID=sa;Password=J" +
            "oseabraham21;Encrypt=False")]
        public string Monolito4amConnectionString17 {
            get {
                return ((string)(this["Monolito4amConnectionString17"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Monolito4amDB.mssql.somee.com;Initial Catalog=Monolito4amDB;User ID=J" +
            "ose_Abraham_SQLLogin_1;Password=35hf8c9xku;Encrypt=False;TrustServerCertificate=" +
            "True")]
        public string Monolito4amDBConnectionString {
            get {
                return ((string)(this["Monolito4amDBConnectionString"]));
            }
        }
    }
}
